language: node_js
node_js:
- '4.0'
- '8.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Dg1g8WfsY5ZGeE57woY1DcZ6DX/1Hs+Ae7RUQCX1Aurn+wQ2KovbliCA1Vux44THubAkCp6IRzWY9Gf+WG7ETcZlNX6evjmRuiY6bIb1l1A3xwoOsh0HBFM/xd7zZLNO9uzwfHllRvxO/1iS6lcrTCMaBgnXfO6M7+y93fhYDY/t2L5tY7dcvZkVib82KeBE04CW6KGw7qWCRpzUmeIivG/J9UUZwQotxZyn0c9qsSmfHFtCl0SD8lwbPyK7jVxKx8hRMtNZ/s2EHA/kx+/exhwu+X+3gXyw9wHk+lj3v77rNmUa7ISzdgHoY+aGaz9OnpA+xU/lazFVVa6iXcMg8ScM/T5Hb4lXydajlOTZWndxBJatTlPX980l17IIu9C8JmXfs0u3lK+xLMzS5P2g0W5wTjQaZkVAGr4hBeXjn1muZAuNyhdhbOFZ0zX402RN3FHelABtGlrROfC5IngB9nAAyr7/LEyMKbdLt/gZvHv2oamfsf0coFpOd9GJFEaNeeH1V8RBg27YhLDbXPpjVNqCKpxaTsonSbq3VIUM5A18ZwM0bS6aARoswSMuM2GoggM5dsLHh3AEdhG9wxFubDh92N3E8lhjAgPerN+CpTBsgCcn7PNEF0jf5sFsZnI6EzPFLYk/g8kmEXPcYzOCAjEgZkEJJkL47rBgjRaJH2w=
  file:
    - "retext-passive.js"
    - "retext-passive.min.js"
  on:
    tags: true
    node: '9.0'
